spring:
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/rent_db"
      maximum-pool-size: 15
      driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1111
    url: "jdbc:postgresql://localhost:5432/rent_db"
---
  flyway:
    baseline-on-migrate: true
    baseline-version: 1.003
---
server:
  port: 8080
---
jwt:
  secret: qwepuisdhfaksdjflsdfn12321___**
  expiration: 3600000

