spring:
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/rent_db"
      maximum-pool-size: 10
      driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1111
    url: "jdbc:postgresql://localhost:5432/rent_db"
server:
  port: 8081
